POST http://localhost:3000/booking
content-type: application/json
authorization: Bearer [place your token here]

{
    "date": "2025-03-10",
    "time": "09:00",
    "barberId": 1,
    "clientId": 2,
    "services": [1]
}