POST http://localhost:3000/booking
content-type: application/json
authorization: Bearer [place your token here]

{
    "day": 10,
    "year": 2025,
    "month": 3,
    "hour": 16,
    "minutes": 0,
    "barberId": 1,
    "clientId": 2,
    "services": [1]
}