GET http://localhost:3000/me
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MDY4OTA1OX0.owKgBCbORg7K-iszdctiP_eweUkNpCqLM8W0CCh6iDo