DELETE http://localhost:3000/booking/15
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MDc1MTIzOX0.i0iFLiXR6fSYm_KxiaF0QN6ty8hwF9WMBaCpS_1EHaw